apiVersion:                   extensions/v1beta1
kind:                         Deployment
metadata:
name:                         webserver
spec:
  replicas:                   1
  template:
    metadata:
      labels:
        app:                  nginx
    spec:
      containers:
      - name:
        image:
          ports:
          - containerPort:    80
        livenessProbe:
          initialDelaySecond: 2
          periodSeconds:      10
          httpGet:
            path:             /
            port:             80
        readinessProbe:
          initialDelaySecond: 2
          periodSeconds:      10
          httpGet:
            path:             /
            port:             80
